### ISSUE TITLE
Präsentation

### ISSUE THREAD

**Issue by Rexphel** [JayReturns/SteakLasagne#171]
joa also hmm iwi sollte das gemacht werden oder? (┛ಠ_ಠ)┛彡┻━┻

**Comment by JayReturns** [comment]
guys... this cannot be a wontfix. our Note depends on it :(

**Comment by AlexSchmitz222** [comment]
done^^

Lukasd1702 was a great help @ this.

**Comment by JayReturns** [comment]
^^
