### ISSUE TITLE
Speichern der Benutzer

### ISSUE THREAD

**Issue by JayReturns** [JayReturns/SteakLasagne#34]
User Object anlegen und mit Transaction verknüpfen.
Passendes Datenbankupdate vorbereiten.

**Comment by Rexphel** [comment]
Das Feature wurde im issue #52 Nutzer Auth. Mit Keycloak implementiert. Können das Issue schließen oder?

**Comment by JayReturns** [comment]
Nein. Erstell bitte einen Pull Request mit deinem Code, der wird dann von mir, Colin oder Lukas reviewd und dann gemerged. Im PR kannst du dann "Closes #52" schreiben, damit der Issue automatisch geschlossen wird.
