### ISSUE TITLE
Add Websecurity Config

### ISSUE THREAD

**Issue by Rexphel** [JayReturns/SteakLasagne#45]
Wäre warscheinlich wichtig. Auch wegen CORS. Ist aber auch ne grundlage für User Auth daher soll ich mich da mal dran hängen?

```@EnableWebSecurity
public class SecurityConfig extends WebSecurityConfigurerAdapter{
  @Override
  public void configure(HttpSecurity httpSecurity) throws Exeption {
    httpSecurity.csrf().disable()
      .authorizeRequests()
      .antMatchers("/api/auth/**")
      .permitAll()
      .anyRequest()
      .authenticated();```

**Comment by JayReturns** [comment]
Ist implementiert
https://github.com/JayReturns/SteakLasagne/blob/develop/sl-server/src/main/java/com/github/jayreturns/slserver/shared/api/configuration/SecurityConfig.java#L23
